import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LinkBox from '../src/Components/LinkBox.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Andrew Graves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"/> 
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hi, I'm <br/> <strong>Andrew Graves</strong>
        </h1>
        <div style={{alignItems: 'start'}}>
          <p className={styles.caption}>What i'm currently working on...</p>
          <a style={{display: 'flex', flexDirection: 'row', justifyContent: 'left', position: 'relative'}} href="https://jotitdown.app" target="_blank" className={styles.card}>
            <div style={{display: 'flex', flexDirection: 'column', justifyContent: 'center', marginRight: '16px'}}>
              <Image src="/jot.png" layout='fixed' width={87} height={70}/>
            </div>
            <p className={styles.paragraph}><strong>Jot</strong> is a <strong>multi-platform, list-taking</strong><br/>application in beta. I work mainly on the <br/><strong>design</strong> and the <strong>Android application</strong> but I do<br/> work on the iOS app occasionally.</p>
          </a>
          <div style={{marginTop: '32px'}}>
            <p className={styles.caption}>Other links...</p>
            <div style={{display: 'flex', flexDirection: 'row', justifyContent: 'left'}}>
              <LinkBox link="https://www.linkedin.com/in/andrewcgraves/" imgSrc="/linkedInLogo.png" width={56} height={56}/>
              <LinkBox link="https://github.com/andrewcgraves" imgSrc="/githubLogo.png" width={56} height={56}/>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
